#ifndef _H_SWS_DEF_H_
#define _H_SWS_DEF_H_
#define UNICODE
#include <Windows.h>

#define DWMWA_USE_HOSTBACKDROPBRUSH 17            // [set] BOOL, Allows the use of host backdrop brushes for the window.
#define DWMWA_USE_IMMERSIVE_DARK_MODE 20          // [set] BOOL, Allows a window to either use the accent color, or dark, according to the user Color Mode preferences.
#define DWMWA_WINDOW_CORNER_PREFERENCE 33         // [set] WINDOW_CORNER_PREFERENCE, Controls the policy that rounds top-level window corners
#define DWMWA_BORDER_COLOR 34                     // [set] COLORREF, The color of the thin border around a top-level window
#define DWMWA_CAPTION_COLOR 35                    // [set] COLORREF, The color of the caption
#define DWMWA_TEXT_COLOR 36                       // [set] COLORREF, The color of the caption text
#define DWMWA_VISIBLE_FRAME_BORDER_THICKNESS 37   // [get] UINT, width of the visible border around a thick frame window
#define DWMWA_MICA_EFFFECT 1029

#define DWMWCP_DEFAULT 0
#define DWMWCP_DONOTROUND 1
#define DWMWCP_ROUND 2
#define DWMWCP_ROUNDSMALL 3

#define DEFAULT_DPI_X 96.0
#define DEFAULT_DPI_Y 96.0

#define SWS_UWP_ICON_SCALE_FACTOR 0.7

#define SWS_WINDOWSWITCHER_CLASSNAME "SimpleWindowSwitcher"
#define SWS_WINDOWSWITCHER_BACKGROUND_COLOR RGB(0, 0, 0)
#define SWS_WINDOWSWITCHER_BACKGROUND_COLOR_LIGHT RGB(210, 210, 210)
#define SWS_WINDOWSWITCHER_CONTOUR_COLOR RGB(255, 255, 255)
#define SWS_WINDOWSWITCHER_CONTOUR_COLOR_LIGHT RGB(70, 70, 70)
#define SWS_WINDOWSWITCHER_TEXT_COLOR RGB(255, 255, 255)
#define SWS_WINDOWSWITCHER_TEXT_COLOR_LIGHT RGB(0, 0, 0)
#define SWS_WINDOWSWITCHER_CLOSE_COLOR RGB(196, 43, 28)
#define SWS_WINDOWSWITCHER_CONTOUR_SIZE 2
#define SWS_WINDOWSWITCHER_HIGHLIGHT_SIZE 1
#define SWS_WINDOWSWITCHER_THEME_CLASS "ControlPanelStyle"
#define SWS_WINDOWSWITCHER_THEME_INDEX 8
#define SWS_FONT_NAME "Segoe UI"
#define SWS_FONT_SIZE -12
#define SWS_FONT_SIZE2 -24

#define SWS_WINDOWFLAG_IS_ON_WINDOW 0b1
#define SWS_WINDOWFLAG_IS_ON_THUMBNAIL 0b10
#define SWS_WINDOWFLAG_IS_ON_CLOSE 0b100

#define SWS_WINDOWSWITCHERLAYOUT_INCLUDE_WALLPAPER TRUE
#define SWS_WINDOWSWITCHERLAYOUT_WALLPAPER_ALWAYS_LAST FALSE
#define SWS_WINDOWSWITCHERLAYOUT_WALLPAPER_TOGGLE FALSE
#define SWS_WINDOWSWITCHERLAYOUT_PERCENTAGEWIDTH 80
#define SWS_WINDOWSWITCHERLAYOUT_PERCENTAGEHEIGHT 80
#define SWS_WINDOWSWITCHERLAYOUT_ROWHEIGHT 250
#define SWS_WINDOWSWITCHERLAYOUT_MAX_TILE_WIDTH 2.0

#define SWS_WINDOWSWITCHERLAYOUT_MASTER_PADDING_TOP 40
#define SWS_WINDOWSWITCHERLAYOUT_MASTER_PADDING_LEFT SWS_WINDOWSWITCHERLAYOUT_MASTER_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_MASTER_PADDING_BOTTOM SWS_WINDOWSWITCHERLAYOUT_MASTER_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_MASTER_PADDING_RIGHT SWS_WINDOWSWITCHERLAYOUT_MASTER_PADDING_TOP

#define SWS_WINDOWSWITCHERLAYOUT_ELEMENT_PADDING_TOP 5
#define SWS_WINDOWSWITCHERLAYOUT_ELEMENT_PADDING_LEFT 2
#define SWS_WINDOWSWITCHERLAYOUT_ELEMENT_PADDING_BOTTOM 5
#define SWS_WINDOWSWITCHERLAYOUT_ELEMENT_PADDING_RIGHT 2

#define SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP 7
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_LEFT SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_BOTTOM SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_RIGHT SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP

#define SWS_WINDOWSWITCHERLAYOUT_PADDING_DIVIDER_HORIZONTAL SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_DIVIDER_VERTICAL SWS_WINDOWSWITCHERLAYOUT_PADDING_LEFT

#define SWS_WINDOWSWITCHERLAYOUT_ROWTITLEHEIGHT 30
#define SWS_WINDOWSWITCHERLAYOUT_PERCENTAGEICON 70
#define SWS_WINDOWSWITCHERLAYOUT_COMPUTE_DIRECTION_INITIAL 0
#define SWS_WINDOWSWITCHERLAYOUT_COMPUTE_DIRECTION_FORWARD 1
#define SWS_WINDOWSWITCHERLAYOUT_COMPUTE_DIRECTION_BACKWARD -1

#define SWS_VECTOR_CAPACITY 20
#endif
