#ifndef _H_SWS_DEF_H_
#define _H_SWS_DEF_H_
#define UNICODE
#include <Windows.h>

#define COMPILE_AS_LIBRARY

#define DEFAULT_DPI_X 96.0
#define DEFAULT_DPI_Y 96.0

#define SWS_WINDOWSWITCHER_CLASSNAME "SimpleWindowSwitcher"
#define SWS_WINDOWSWITCHER_BACKGROUND_COLOR RGB(0, 0, 0)
#define SWS_WINDOWSWITCHER_CONTOUR_COLOR RGB(255, 255, 255)
#define SWS_WINDOWSWITCHER_TEXT_COLOR RGB(255, 255, 255)
#define SWS_WINDOWSWITCHER_CONTOUR_SIZE 2
#define SWS_WINDOWSWITCHER_THEME_CLASS "ControlPanelStyle"
#define SWS_WINDOWSWITCHER_THEME_INDEX 8

#define SWS_WINDOWSWITCHERLAYOUT_INCLUDE_WALLPAPER 1
#define SWS_WINDOWSWITCHERLAYOUT_PERCENTAGEWIDTH 60
#define SWS_WINDOWSWITCHERLAYOUT_PERCENTAGEHEIGHT 60
#define SWS_WINDOWSWITCHERLAYOUT_ROWHEIGHT 250
#define SWS_WINDOWSWITCHERLAYOUT_PADDING 25
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP 8
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_LEFT SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_BOTTOM SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_PADDING_RIGHT SWS_WINDOWSWITCHERLAYOUT_PADDING_TOP
#define SWS_WINDOWSWITCHERLAYOUT_ROWTITLEHEIGHT 30
#define SWS_WINDOWSWITCHERLAYOUT_PERCENTAGEICON 70
#define SWS_WINDOWSWITCHERLAYOUT_COMPUTE_DIRECTION_INITIAL 0
#define SWS_WINDOWSWITCHERLAYOUT_COMPUTE_DIRECTION_FORWARD 1
#define SWS_WINDOWSWITCHERLAYOUT_COMPUTE_DIRECTION_BACKWARD -1

#define SWS_VECTOR_CAPACITY 3
#endif
